### ISSUE TITLE
#each style helpers for months & weekdays

### ISSUE THREAD

**Issue by lb-** [lb-/moment-helpers#11]
**Comment +1s if this would be a useful feature + add suggestions**

Not sure if people would find this helpful but might be nice in 1.0.4 (with index available in #each & the #let), need to investigate best way to implement.

## eg.
```html
<ul>
{{#each moMonths}}
 <li>{{this}}</li>
{{/each}}
</ul>
```
Returns
```html
<ul>
  <li>January</li>
  <li>February</li>
  <li>March</li>
  <li>...</li>
</ul>
```

### List
* moMonths
* moMonthsShort
* moWeekdays
* moWeekdaysShort
* moWeekdaysMin

Maybe join moMonths variants into one helper eg. `{{#each moArray 'months/monthsShort/weekdays/weekdaysMin'}}`

**Comment by djhi** [comment]
I probably won't use it as I usually use a datepicker with some config to get only months or so, but it's nevertheless a nice feature.

**Comment by lb-** [comment]
Closing this, not much interest - may reopen later.
