### ISSUE TITLE
how to have 2 hours and 20 minutes ?

### ISSUE THREAD

**Issue by ramstein74** [lb-/moment-helpers#16]
hello i´m using your package.
Its nice but for me i need more granular date info

I'm using moFromNow that gives me 

2 hours ago

however only reaching 3 hours this value changes.

I need to distinguish records that have 2 hours but different minutes like

2 hours 20 minutes ago
2 hours 40 minuts ago..
etc

how can i have minutes after the hour ?

i dont care about seconds...

Thank you

**Comment by lb-** [comment]
@ramstein74 unfortunately that is not part of the moment js core and I wont be able to integrate that with the moment helpers any time soon.

however, one approach would be for you to use this moment js plug in
http://codebox.org.uk/pages/moment-date-range-plugin

It will give you the resolution all the way down to seconds, but you could refine your datetime object to not have seconds in it.
