### ISSUE TITLE
how to change locale?

### ISSUE THREAD

**Issue by bjesus** [lb-/moment-helpers#17]
(I've been trying to get this working for an hour or so but I don't seem to get any closer...)

I'm not looking into reactivity specifically, only to set the locale once and for all. What's the Right Way to do it?

I've tried adding other Moment.js packages that have my locale in it, and `moment.locale('mylocale')` seems to work just fine. but the helpers still show up in English, even after `mo.setLocale('mylocale')`

What am I missing?

Thanks

**Comment by lb-** [comment]
@bjesus sorry for the delay & that you are having trouble getting this working.

Can you clarify what other package you using (the one with the locale in it), this feature is not well tested as it is hard to test with multiple sets of different packages (you can only load tests for one set of packages currently).

Or do you have your code available online so I can give it a try.

**Comment by bjesus** [comment]
What package should I use? I think I've tried almost all of them :-( If you know of a specific setup that works I'll happily change to it, I'm just looking for a way to get this working.

I've pushed the code here: https://github.com/bjesus/wyt

**Comment by lb-** [comment]
@bjesus got it working, in your packages file, replace mrt:moment with momentjs:moment

or simply
```bash
  meteor remove mrt:moment
  meteor add momentjs:moment
```

**Comment by lb-** [comment]
Not exactly sure what the issue was but probably a version conflict between the old (deprecated) mrt moment package and the new official momentjs package

**Comment by lb-** [comment]
![screen shot 2015-05-30 at 7 09 40 pm](https://cloud.githubusercontent.com/assets/1396140/7896509/bef02e76-06ff-11e5-945a-301b0fb11f7b.png)

See it working with that change in screenshot

**Comment by bjesus** [comment]
Thanks! it works now! I'm sure I've tried this package too but maybe without the inline language settings I now have @ `wyt.js`.
Thanks a lot.

**Comment by lb-** [comment]
Glad I could help man, hope the rest of the app goes great!
