### ISSUE TITLE
debug option issue

### ISSUE THREAD

**Issue by javaknight** [lb-/moment-helpers#2]
So I had an issue with the date I was providing to moFormat being '' (I think). Debug:true wasn't picking it up and alerting me that it was a bad date. Then moment kicked in and told me:

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

And the formatted date string returned was just blank

I also turned on returnNowIfDateNotGiven: true 

and the returned string was still blank and the same message appeared in console.

**Comment by lb-** [comment]
@javaknight I know you closed this issue but this was a separate issue and has now been fixed
