### ISSUE TITLE
calendar() function not implemented yet

### ISSUE THREAD

**Issue by hamoid** [lb-/moment-helpers#21]
The only function I'm using from momentjs is [calendar()](http://momentjs.com/docs/#/displaying/calendar-time/), and it's not currently implemented in moment-helpers.

How could I add it to my project? Before I found moment-helpers it was working, but it was not reactive. I need it to be reactive, so when I choose a language the dates are also updated.

Thanks :)

**Comment by lb-** [comment]
So something like


   - {{moCalendar date referenceDate}}
   - {{moCalendar d=date r=referenceDate}}

If the date given is yesterday at 1pm it will show 'Yesterday at 1:00pm'

If you do not provide a date to the helper it should return a reactive
'now' meaning it will update, so lets say it is 11:59pm and the crosses
over the week it will then say 'last Sunday' or something like that.

And yes if you use the mo.setLocale it should also update the language
reactively. Remember that you need to check you do not have multiple
versions of Moment Js running (check your dependencies).

I have not implemented moCalendar yet, away on holidays at the moment but
can look into it asap.



On Saturday, 20 June 2015, Abe Pazos <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> The only function I'm using from momentjs is calendar()
> <http://momentjs.com/docs/#/displaying/calendar-time/>, and it's not
> currently implemented in moment-helpers.
>
> How could I add it to my project? Before I found moment-helpers it was
> working, but it was not reactive. I need it to be reactive, so when I
> choose a language the dates are also updated.
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lb-/moment-helpers/issues/21>.
>


-- 
|b

+61 414 446 068
@_lb_ <http://twitter.com/_lb_> | fb.me/lb.ben | lb.ee

**Comment by hamoid** [comment]
Thanks for your comment. I threw this, based on one of the existing functions, in a client folder:

```
Template.registerHelper('moCalendar', function () {
  // Calling this reactive property ensure the helper is updated
  var locale = mo.currentLocale.get();

  //enables the arguments to be provided as args or vars
  //eg. {{moFormat date=myDate}} or {{moFormat myDate}} will do the same thing
  var args = _.toArray(arguments);
  var kw = args.pop();
  var date = args[0] || kw.hash.d;

  //processes what was given to ensure we end up with a moment object
  var moDate = mo._getMoment(date);

  // fail silently if the date is not worked out to be a moment
  if (moDate) {
    return moDate.calendar();
  }

  return;
});
```

and it works :)

**Comment by lb-** [comment]
@hamoid - epic stuff! I will get that put in with some tests when I can. Thanks man.

**Comment by lb-** [comment]
@hamoid the latest version of this package now up and contains this feature.

**Comment by hamoid** [comment]
Great! thanks :)
