### ISSUE TITLE
changing language

### ISSUE THREAD

**Issue by kamil7732** [lb-/moment-helpers#28]
Hi,
first of all great plugin.
Could you kindly inform me how to change the language?
I'm trying to push mo.setLocale('es'); nothing happens. Does your plugin include moment with localisation?

**Comment by lb-** [comment]
@kamil7732 thanks for your comment & question, love to hear you are using the package.

There are no localisation libraries included with this package, you have a few options;

1. Also add this package (note it may duplicate moment js library) https://atmospherejs.com/jeeeyul/moment-with-langs
2. Add this langs package (seems less used but looks like it ONLY has the languages, not the moment js library also) https://atmospherejs.com/gildaspk/moment-languages
3. Copy & paste the languages you want to a file in lib & load it in that way, as per the documentation here: http://momentjs.com/docs/#/i18n/changing-locale/ using something like `moment.locale('es', {...});`

Hope that helps, I will create an issue to put better documentation about locales (had this question a few times now).
