### ISSUE TITLE
does not accept YYYYMMDD / checking validity

### ISSUE THREAD

**Issue by javaknight** [lb-/moment-helpers#3]
If you provide a date input to moFormat template helper as such
{{ moFormat '20150105' 'YYYY-MM-DD' }}

it doesn't work and fails silently. also debug doesn't alert you also-

Expected result 
'2015-01-05'

also, it gets more interesting. From the javascript console:
moment("20150515").isValid();
false
 moment("20150515", 'YYYYMMDD').isValid();
true

maybe the best solution would be to perform the valid check with the suggested token...?

**Comment by javaknight** [comment]
I think one way to solve this would be to take 3 arguments 
1. the date
2. a token describing the input format of the date (YYYYMMDD)
3. a token describing the output format of the date (MM/DD/YYYY)

**Comment by javaknight** [comment]
btw (https://github.com/moment/moment/issues/1407) describes the issue in great detail. hope it helps.

**Comment by lb-** [comment]
@javaknight input format token could be an option but what if I used a date string parser (if a string is provided) such as this: https://github.com/borgar/dateutil

another way to approach it would be if you want to provide a date as a string you need to provide it in some format like '03042015|DDMMYYYY'.

**Comment by lb-** [comment]
Going to just go with the built in javascript date parser and also approach with the string format
 like '03042015|DDMMYYYY'

**Comment by lb-** [comment]
@javaknight see how it goes & let me know if the readme makes sense
https://github.com/lb-/moment-helpers#providing-date-strings
