### ISSUE TITLE
Issue on Meteor 1.3: m._d.getTime is not a function

### ISSUE THREAD

**Issue by serkandurusoy** [lb-/moment-helpers#38]
Exception in template helper: TypeError: m._d.getTime is not a function with not much clue to work on

**Comment by serkandurusoy** [comment]
moFormat seems fine but moFrom throws that error

**Comment by serkandurusoy** [comment]
@lb- this line is where it fails:

https://github.com/lb-/moment-helpers/blob/master/client.js#L62

**Comment by lb-** [comment]
@serkandurusoy thank you for the heads up, I will check it out over the weekend and fix it up.

**Comment by lb-** [comment]
@serkandurusoy just an update, gave a shot at this last night, updated a few things but could not get to the bottom of it, will keep at it, hope it is not causing too much trouble.

**Comment by serkandurusoy** [comment]
Thanks a lot for looking into it.

I've temporarily created my own helper to substitute that, so I'm fine at the moment.

But I'd be happy to test and switch back once you roll out an update.

**Comment by cluxter** [comment]
Having the same issue here

**Comment by lb-** [comment]
@serkandurusoy @cluxter can you please test the latest version on Atmosphere, let me know if this resolves the issue for you

**Comment by cluxter** [comment]
@lb- : it works great on my app. Thanks a lot!

**Comment by serkandurusoy** [comment]
@lb- yes it is fixed for me as well. thank you.
