### ISSUE TITLE
Add withoutSuffix for moFrom

### ISSUE THREAD

**Issue by kroman0** [lb-/moment-helpers#43]
http://momentjs.com/docs/#/displaying/from/

> Like moment#fromNow, passing true as the second parameter returns value without the suffix. This is useful wherever you need to have a human readable length of time.

**Comment by lb-** [comment]
Thanks for the suggestion, I will look at getting this happening over the weekend.

**Comment by lb-** [comment]
thanks @kroman0 I will get this onto atmosphere after updating tests.
